In [39]:
import pandas as pd
import os
import numpy as np

Q1. Pandas version

In [2]:
pd.__version__


'2.2.2'

In [11]:
home_dir = os.getcwd()

In [12]:
df = pd.read_csv(f'{home_dir}/laptops.csv')

Q2. Records count - How many records are in the dataset?

In [14]:
record_count = len(df)
print (record_count)

2160


Q3. Laptop brands - How many laptop brands are presented in the dataset?

In [15]:
df_laptop_brands = df['Brand'].nunique()
print(df_laptop_brands)

27


Q4. Missing values - How many columns in the dataset have missing values?

In [19]:
# Count missing values in each column
missing_values_per_column = df.isnull().sum()

# Filter columns that have missing values
columns_with_missing_values = missing_values_per_column[missing_values_per_column > 0]

# Calculate how many columns have missing values
num_columns_with_missing_values = len(columns_with_missing_values)

print(f"Number of columns with missing values: {num_columns_with_missing_values}")
print("Columns with missing values:")
print(columns_with_missing_values)

Number of columns with missing values: 3
Columns with missing values:
Storage type      42
GPU             1371
Screen             4
dtype: int64


Q5. Maximum final price - What's the maximum final price of Dell notebooks in the dataset?

In [23]:
# Filter rows where Brand is "Dell"
dell_notebooks = df[df['Brand'] == 'Dell']


# Find the maximum final price for Dell notebooks
max_final_price = dell_notebooks['Final Price'].max()

print(f"The maximum final price of Dell notebooks is: {max_final_price}")

The maximum final price of Dell notebooks is: 3936.0


Q6. Median value of Screen

In [24]:
# Find the median value of Screen column in the dataset.
# Convert the 'Screen' column to numeric if it's not already
# This assumes the 'Screen' column has numeric values like screen size (e.g., 13.3, 15.6)
df['Screen'] = pd.to_numeric(df['Screen'], errors='coerce')

# Find the median value of the 'Screen' column
median_screen_value = df['Screen'].median()

print(f"The median value of the Screen column is: {median_screen_value}")

The median value of the Screen column is: 15.6


In [25]:
#Next, calculate the most frequent value of the same Screen column.
# Convert the 'Screen' column to numeric if it's not already
df['Screen'] = pd.to_numeric(df['Screen'], errors='coerce')

# Find the most frequent value (mode) in the 'Screen' column
most_frequent_screen_value = df['Screen'].mode()[0]

print(f"The most frequent value of the Screen column is: {most_frequent_screen_value}")

The most frequent value of the Screen column is: 15.6


In [28]:
#Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
# Convert the 'Screen' column to numeric if it's not already
df['Screen'] = pd.to_numeric(df['Screen'], errors='coerce')

# Find the most frequent value (mode) in the 'Screen' column
most_frequent_screen_value = df['Screen'].mode()[0]

# Use fillna() to replace missing values in the 'Screen' column with the most frequent value
df['Screen'].fillna(most_frequent_screen_value, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_20116\829428705.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Screen'].fillna(most_frequent_screen_value, inplace=True)


In [29]:
# Now, calculate the median of the 'Screen' column
new_median_screen_value = df['Screen'].median()

print(f"The new median value of the Screen column is: {new_median_screen_value}")

The new median value of the Screen column is: 15.6


Q7. Sum of weights

In [48]:
# 1 Filter the DataFrame to select only the rows where the 'Brand' column is 'Innjoo'
innjoo_laptops = df[df['Brand'] == 'Innjoo']

# 2 Select only the 'RAM', 'Storage', and 'Screen' columns
selected_columns = innjoo_laptops[['RAM', 'Storage', 'Screen']]

# 3 Get the underlying NumPy array and assign it to X
X = selected_columns.to_numpy()


# 4 Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
X_transpose = X.T

XTX = np.dot(X_transpose, X)


# 5 Compute the inverse of XTX
try:
    XTX_inv = np.linalg.inv(XTX)
    print("Inverse of XTX:")
    print(XTX_inv)
except np.linalg.LinAlgError:
    print("The matrix XTX is singular and cannot be inverted.")
    
    
# 6 Create the array y with the specified values
y = np.array([1100, 1300, 800, 900, 1000, 1100])

# Perform the operations only if XTX_inv is valid
if XTX_inv is not None:
    # Multiply the inverse of XTX with the transpose of X
    result = XTX_inv @ X_transpose
    
    # Now multiply the result by y to get w
    w = result @ y
    
    # Calculate the sum of all elements in w
    sum_of_w = np.sum(w)
    # Print the final result w
    print("Result w:")
    print(sum_of_w)

Inverse of XTX:
[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]
Result w:
91.2998806299555
